DELIMITER $$
drop procedure if exists pr_sta_ins_benpost_15042025;
CREATE DEFINER=`root`@`%` PROCEDURE `pr_sta_ins_benpost_15042025`(
  in in_file_gid int,
  in in_depository_code char(1),
  in in_isin_id varchar(16),
  in in_dp_id varchar(16),
  in in_client_id varchar(32),
  in in_sebi_reg_no varchar(32),
  in in_benpost_date varchar(16),
  in in_share_count int,
  in in_lockin int,
  in in_pledge int,
  in in_holder1_name varchar(128),
  in in_holder1_fh_name varchar(128),
  in in_holder2_name varchar(128),
  in in_holder2_fh_name varchar(128),
  in in_holder3_name varchar(128),
  in in_holder3_fh_name varchar(128),
  in in_holder1_addr1 varchar(128),
  in in_holder1_addr2 varchar(128),
  in in_holder1_addr3 varchar(128),
  in in_holder1_city varchar(128),
  in in_holder1_state varchar(128),
  in in_holder1_country varchar(128),
  in in_holder1_pin varchar(16),
  in in_holder1_pan varchar(16),
  in in_holder2_pan varchar(16),
  in in_holder3_pan varchar(16),
  in in_holder1_contact_no varchar(128),
  in in_holder1_fax_no varchar(128),
  in in_holder1_email_id varchar(128),
  in in_holder2_email_id varchar(128),
  in in_holder3_email_id varchar(128),
  in in_holder1_per_addr1 varchar(128),
  in in_holder1_per_addr2 varchar(128),
  in in_holder1_per_addr3 varchar(128),
  in in_holder1_per_city varchar(128),
  in in_holder1_per_state varchar(128),
  in in_holder1_per_country varchar(128),
  in in_holder1_per_pin varchar(16),
  in in_nominee_name varchar(128),
  in in_nominee_part1 varchar(128),
  in in_nominee_part2 varchar(128),
  in in_nominee_part3 varchar(128),
  in in_nominee_part4 varchar(128),
  in in_nominee_part5 varchar(128),
  in in_bank_name varchar(128),
  in in_bank_addr1 varchar(128),
  in in_bank_addr2 varchar(128),
  in in_bank_addr3 varchar(128),
  in in_bank_city varchar(128),
  in in_bank_state varchar(128),
  in in_bank_country varchar(128),
  in in_bank_pin varchar(16),
  in in_bank_acc_no varchar(32),
  in in_bank_acc_type varchar(32),
  in in_bank_micr_code varchar(16),
  in in_bank_ifsc_code varchar(32),
  in in_rbi_ref_no varchar(32),
  in in_rbi_app_date varchar(16),
  in in_bene_type varchar(16),
  in in_bene_subtype varchar(16),
  in in_bene_acccat varchar(16),
  in in_bene_occupation varchar(16),
  in in_bene_tax_deduction_status VARCHAR(20),
  in in_bene_status CHAR(2),
  in in_bene_free_positions DECIMAL(15,2),
  in in_bene_block_positions DECIMAL(15,2),
  in in_bene_pledge_with_lockin_position DECIMAL(15,2),
  in in_bene_pledged_unconfirmed_Position DECIMAL(15,2),
  in in_bene_uncnfrm_Pledged_with_Lockin_position DECIMAL(15,2),
  in in_bene_cm_idd_positions DECIMAL(15,2),
  in in_holder1_pan_flag CHAR(1),
  in in_holder2_pan_flag CHAR(1),
  in in_holder3_pan_flag CHAR(1),
  in in_guardian_name VARCHAR(142),
  in in_birth_date date,
  in in_account_status CHAR(1),
  in in_bo_freeze_flag CHAR(1),
  in in_freeze_reason_code INT(2),
  in in_isin_status CHAR(1),
  in in_acc_opening_date date,
  in in_tax_deduction_status INT(2),
  in in_nationality CHAR(3),
  in in_secondary_phone_no VARCHAR(17),
  in in_ecs_mandate_flag CHAR(1),
  in in_divident_bank_currency INT(11),
  in in_free_bal INT(22),
  in in_pending_demat_verification INT(22),
  in in_pending_demat_confirmation INT(22),
  in in_pledge_setup_bal INT(22),
  in in_uid_of_holder1 VARCHAR(15),
  in in_uid_of_holder2 VARCHAR(15),
  in in_uid_of_holder3 VARCHAR(15),
  in in_line_no int,
  in in_errline_flag boolean,
  out out_msg text,
  out out_result int
)
me:BEGIN
  declare err_msg text default '';
  declare err_flag varchar(10) default false;
  declare v_comp_gid int default 0;

  /*DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    set out_msg = 'SQLEXCEPTION';
    set out_result = 0;

    if in_errline_flag = true then
      call pr_sta_ins_errline(in_file_gid,in_line_no,out_msg);
    end if;
  END;*/
  
   DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
    @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
    SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);

    ROLLBACK;
    set out_result = 0;
    set out_msg = @full_error;
    
    if in_errline_flag = true then
      call pr_sta_ins_errline(in_file_gid,in_line_no,out_msg);
    end if;
  END;

  
  
  select comp_gid into v_comp_gid from sta_mst_tcompany
  where isin_id = in_isin_id
  and delete_flag = 'N';

  set v_comp_gid = ifnull(v_comp_gid,0);

  if v_comp_gid = 0 then
    set err_msg := concat(err_msg,'Invalid company,');
    set err_flag := true;
  end if;

  
  

  
  if in_rbi_app_date = '0001-01-01' then
    set in_rbi_app_date := null;
  end if;

  
  if in_benpost_date = '0001-01-01' then
    set err_msg := concat(err_msg,'Invalid benpost date,');
    set err_flag := true;
  end if;

  
  if err_flag = false then
    if exists(select a.benpost_gid from sta_trn_tbenpost as a
      where a.depository_code = in_depository_code
      and a.client_id = in_client_id
      and a.benpost_date = cast(in_benpost_date as date)
      and a.dp_id = in_dp_id
      and a.isin_id = in_isin_id
      and a.delete_flag = 'N') then
      set err_msg := concat(err_msg,'Duplicate record,');
      set err_flag := true;
    end if;
  end if;

  if err_flag = true then
    set out_result = 0;
    set out_msg = err_msg;

    if in_errline_flag = true then
      call pr_sta_ins_errline(in_file_gid,in_line_no,out_msg);
    end if;

    leave me;
  end if;

  START TRANSACTION;

  INSERT INTO sta_trn_tbenpost
  (
    file_gid,
    comp_gid,
    folio_gid,
    depository_code,
    isin_id,
    dp_id,
    client_id,
    sebi_reg_no,
    benpost_date,
    share_count,
    holder1_name,
    holder1_fh_name,
    holder2_name,
    holder2_fh_name,
    holder3_name,
    holder3_fh_name,
    holder1_addr1,
    holder1_addr2,
    holder1_addr3,
    holder1_city,
    holder1_state,
    holder1_country,
    holder1_pin,
    holder1_pan,
    holder2_pan,
    holder3_pan,
    holder1_contact_no,
    holder1_fax_no,
    holder1_email_id,
    holder2_email_id,
    holder3_email_id,
    holder1_per_addr1,
    holder1_per_addr2,
    holder1_per_addr3,
    holder1_per_city,
    holder1_per_state,
    holder1_per_country,
    holder1_per_pin,
    nominee_name,
    nominee_part1,
    nominee_part2,
    nominee_part3,
    nominee_part4,
    nominee_part5,
    bank_name,
    bank_addr1,
    bank_addr2,
    bank_addr3,
    bank_city,
    bank_state,
    bank_country,
    bank_pin,
    bank_acc_no,
    bank_acc_type,
    bank_micr_code,
    bank_ifsc_code,
    rbi_ref_no,
    rbi_app_date,
    bene_type,
    bene_subtype,
    bene_acccat,
    bene_occupation,
    lockin,
    pledge,
    bene_tax_deduction_status,
    bene_status,
    bene_free_positions,
    bene_block_positions,
    bene_pledge_with_lockin_position,
    bene_pledged_unconfirmed_Position,
    bene_uncnfrm_Pledged_with_Lockin_position,
    bene_cm_idd_positions,
    holder1_pan_flag,
    holder2_pan_flag,
    holder3_pan_flag,
    guardian_name,
    birth_date,
    account_status,
    bo_freeze_flag,
    freeze_reason_code,
    isin_status,
    acc_opening_date,
    tax_deduction_status,
    nationality,
    secondary_phone_no,
    ecs_mandate_flag,
    divident_bank_currency,
    free_bal,
    pending_demat_verification,
    pending_demat_confirmation,
    pledge_setup_bal,
    uid_of_holder1,
    uid_of_holder2,
    uid_of_holder3
  )
  VALUES
  (
    in_file_gid,
    v_comp_gid,
    0,
    in_depository_code,
    in_isin_id,
    in_dp_id,
    in_client_id,
    in_sebi_reg_no,
    cast(in_benpost_date as date),
    in_share_count,
    in_holder1_name,
    in_holder1_fh_name,
    in_holder2_name,
    in_holder2_fh_name,
    in_holder3_name,
    in_holder3_fh_name,
    in_holder1_addr1,
    in_holder1_addr2,
    in_holder1_addr3,
    in_holder1_city,
    in_holder1_state,
    in_holder1_country,
    in_holder1_pin,
    in_holder1_pan,
    in_holder2_pan,
    in_holder3_pan,
    in_holder1_contact_no,
    in_holder1_fax_no,
    in_holder1_email_id,
    in_holder2_email_id,
    in_holder3_email_id,
    in_holder1_per_addr1,
    in_holder1_per_addr2,
    in_holder1_per_addr3,
    in_holder1_per_city,
    in_holder1_per_state,
    in_holder1_per_country,
    in_holder1_per_pin,
    in_nominee_name,
    in_nominee_part1,
    in_nominee_part2,
    in_nominee_part3,
    in_nominee_part4,
    in_nominee_part5,
    in_bank_name,
    in_bank_addr1,
    in_bank_addr2,
    in_bank_addr3,
    in_bank_city,
    in_bank_state,
    in_bank_country,
    in_bank_pin,
    in_bank_acc_no,
    in_bank_acc_type,
    in_bank_micr_code,
    in_bank_ifsc_code,
    in_rbi_ref_no,
    cast(in_rbi_app_date as date),
    in_bene_type,
    in_bene_subtype,
    in_bene_acccat,
    in_bene_occupation,
    in_lockin,
    in_pledge,
    in_bene_tax_deduction_status,
	in_bene_status,
	in_bene_free_positions,
	in_bene_block_positions,
	in_bene_pledge_with_lockin_position,
	in_bene_pledged_unconfirmed_Position,
	in_bene_uncnfrm_Pledged_with_Lockin_position,
	in_bene_cm_idd_positions,
	in_holder1_pan_flag,
	in_holder2_pan_flag,
	in_holder3_pan_flag,
	in_guardian_name,
    cast(in_birth_date as date),
	in_account_status,
	in_bo_freeze_flag,
	in_freeze_reason_code,
	in_isin_status,
    cast(in_acc_opening_date as date),
	in_tax_deduction_status,
	in_nationality,
	in_secondary_phone_no,
	in_ecs_mandate_flag,
	in_divident_bank_currency,
	in_free_bal,
	in_pending_demat_verification,
	in_pending_demat_confirmation,
	in_pledge_setup_bal,
	in_uid_of_holder1,
	in_uid_of_holder2,
	in_uid_of_holder3
  );

INSERT INTO sta_trn_tcurrentbenpost
  (
    file_gid,
    comp_gid,
    folio_gid,
    depository_code,
    isin_id,
    dp_id,
    client_id,
    sebi_reg_no,
    benpost_date,
    share_count,
    holder1_name,
    holder1_fh_name,
    holder2_name,
    holder2_fh_name,
    holder3_name,
    holder3_fh_name,
    holder1_addr1,
    holder1_addr2,
    holder1_addr3,
    holder1_city,
    holder1_state,
    holder1_country,
    holder1_pin,
    holder1_pan,
    holder2_pan,
    holder3_pan,
    holder1_contact_no,
    holder1_fax_no,
    holder1_email_id,
    holder2_email_id,
    holder3_email_id,
    holder1_per_addr1,
    holder1_per_addr2,
    holder1_per_addr3,
    holder1_per_city,
    holder1_per_state,
    holder1_per_country,
    holder1_per_pin,
    nominee_name,
    nominee_part1,
    nominee_part2,
    nominee_part3,
    nominee_part4,
    nominee_part5,
    bank_name,
    bank_addr1,
    bank_addr2,
    bank_addr3,
    bank_city,
    bank_state,
    bank_country,
    bank_pin,
    bank_acc_no,
    bank_acc_type,
    bank_micr_code,
    bank_ifsc_code,
    rbi_ref_no,
    rbi_app_date,
    bene_type,
    bene_subtype,
    bene_acccat,
    bene_occupation,
    lockin,
    pledge,
    bene_tax_deduction_status,
    bene_status,
    bene_free_positions,
    bene_block_positions,
    bene_pledge_with_lockin_position,
    bene_pledged_unconfirmed_Position,
    bene_uncnfrm_Pledged_with_Lockin_position,
    bene_cm_idd_positions,
    holder1_pan_flag,
    holder2_pan_flag,
    holder3_pan_flag,
    guardian_name,
    birth_date,
    account_status,
    bo_freeze_flag,
    freeze_reason_code,
    isin_status,
    acc_opening_date,
    tax_deduction_status,
    nationality,
    secondary_phone_no,
    ecs_mandate_flag,
    divident_bank_currency,
    free_bal,
    pending_demat_verification,
    pending_demat_confirmation,
    pledge_setup_bal,
    uid_of_holder1,
    uid_of_holder2,
    uid_of_holder3
  )
  VALUES
  (
    in_file_gid,
    v_comp_gid,
    0,
    in_depository_code,
    in_isin_id,
    in_dp_id,
    in_client_id,
    in_sebi_reg_no,
    cast(in_benpost_date as date),
    in_share_count,
    in_holder1_name,
    in_holder1_fh_name,
    in_holder2_name,
    in_holder2_fh_name,
    in_holder3_name,
    in_holder3_fh_name,
    in_holder1_addr1,
    in_holder1_addr2,
    in_holder1_addr3,
    in_holder1_city,
    in_holder1_state,
    in_holder1_country,
    in_holder1_pin,
    in_holder1_pan,
    in_holder2_pan,
    in_holder3_pan,
    in_holder1_contact_no,
    in_holder1_fax_no,
    in_holder1_email_id,
    in_holder2_email_id,
    in_holder3_email_id,
    in_holder1_per_addr1,
    in_holder1_per_addr2,
    in_holder1_per_addr3,
    in_holder1_per_city,
    in_holder1_per_state,
    in_holder1_per_country,
    in_holder1_per_pin,
    in_nominee_name,
    in_nominee_part1,
    in_nominee_part2,
    in_nominee_part3,
    in_nominee_part4,
    in_nominee_part5,
    in_bank_name,
    in_bank_addr1,
    in_bank_addr2,
    in_bank_addr3,
    in_bank_city,
    in_bank_state,
    in_bank_country,
    in_bank_pin,
    in_bank_acc_no,
    in_bank_acc_type,
    in_bank_micr_code,
    in_bank_ifsc_code,
    in_rbi_ref_no,
    cast(in_rbi_app_date as date),
    in_bene_type,
    in_bene_subtype,
    in_bene_acccat,
    in_bene_occupation,
    in_lockin,
    in_pledge,
    in_bene_tax_deduction_status,
	in_bene_status,
	in_bene_free_positions,
	in_bene_block_positions,
	in_bene_pledge_with_lockin_position,
	in_bene_pledged_unconfirmed_Position,
	in_bene_uncnfrm_Pledged_with_Lockin_position,
	in_bene_cm_idd_positions,
	in_holder1_pan_flag,
	in_holder2_pan_flag,
	in_holder3_pan_flag,
	in_guardian_name,
    cast(in_birth_date as date),
	in_account_status,
	in_bo_freeze_flag,
	in_freeze_reason_code,
	in_isin_status,
    cast(in_acc_opening_date as date),
	in_tax_deduction_status,
	in_nationality,
	in_secondary_phone_no,
	in_ecs_mandate_flag,
	in_divident_bank_currency,
	in_free_bal,
	in_pending_demat_verification,
	in_pending_demat_confirmation,
	in_pledge_setup_bal,
	in_uid_of_holder1,
	in_uid_of_holder2,
	in_uid_of_holder3
  );

  COMMIT;

  set out_result = 1;
  set out_msg = 'Record updated successfully !';
 END$$
DELIMITER ;
